### PR TITLE
enable changing the language for fb sdk

### LINKED ISSUE #31: Detect language code from system
Please can you add this feature? :-)

- https://github.com/BurdaMagazinOrg/infinite-theme/blob/8.x-1.x/templates/embeds/api_fb.html.twig#L19

- https://github.com/BurdaMagazinOrg/infinite-theme/blob/8.x-1.x/infinite.theme#L58
 
- https://github.com/BurdaMagazinOrg/infinite-theme/blob/8.x-1.x/templates/system/html.html.twig#L27

As new feature should be FB pixel support:

```<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');

fbq('init', '{{ fb_pixel_id }}');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id={{ fb_pixel_id }}&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->
```

### PR DESCRIPTION
**Pull request by tjwelde**
fixes #31

### CODE REVIEW

**Comment by landsman** [comment]
and what If we want have multilanguage site in future ?

**Comment by tjwelde** [comment]
~We could parse the `ACCEPT_LANGUAGE` header, maybe.~ Please note, that we always need the IETF language code.

**Comment by tjwelde** [comment]
~The problem is also, how we handle caching. Many sites are behind a Varnish cache, so the request won't reach the server at all.~

**Comment by landsman** [comment]
I know about:

```
function THEME_preprocess_node(&$variables) {

    $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    var_dump($language);
    die;
}
```

**Comment by tjwelde** [comment]
I tried that, but it gives just a 2-letter language code and only regards the site language.

**Comment by tjwelde** [comment]
~I think the only possible solution is to get the user language through javascript~

**Comment by tjwelde** [comment]
Ah, now I get what you mean. Yes the issue with your code is, that it gives you just a 2-letter code. We would have to provide some sort of conversion.

**Comment by landsman** [comment]
```return $language . "_" . strtoupper($language);``` will be good - joke.
I think that Language class from PHP can be convert 2-letter code to ISO, but nope.

**Comment by tjwelde** [comment]
Haha, yeah I thought of that too, but it works only for some languages

**Comment by landsman** [comment]
I was found this: https://www.drupal.org/node/1231402

**Comment by dbosen** [comment]
@chrfritsch: could you please review this? Thanks!

**Review by chrfritsch — APPROVED** [review]
Looks good to me. Maybe we should enable metatag_facebook in Thunder by default

**Comment by landsman** [comment]
@chrfritsch It could be great!

**Pull request merged**
