### PR TITLE
merge 8.x-2.x into 8.x-3.x

### PR DESCRIPTION
**Pull request by mgoedecke**

### CODE REVIEW

**Comment by mgoedecke** [comment]
**probably affected issues:** 
- https://jira.burda.com/browse/INREL-3520 (Multiple skyscraper slots - Update Ad Module)
- https://jira.burda.com/browse/INREL-3499 (Remove Second H1 Heading on AMP + website)
- https://jira.burda.com/browse/INREL-3642 (Bug: Author name styling freundin)
- https://jira.burda.com/browse/INREL-3368 (Improve Pinterest Images)
- https://jira.burda.com/browse/INREL-3437 (Overlap of bars in Thunder 8.4 update)
- https://jira.burda.com/browse/INREL-3519 (The infinite scrolling in article streams doesn't work)
- https://jira.burda.com/browse/INREL-2456 (Add Google News structured Data to non-AMP Nodes)

**Review by saviomuc — COMMENTED** [review]
Not sure about https://github.com/BurdaMagazinOrg/infinite-theme/pull/110/files#diff-0e4b605873d197ad8f54779e5d160eb1R12

But otherwise looks fine to me. Any other opionions?

**Review by alxshll — COMMENTED** [review]
Not sure about infinite.theme line 49 and templates/system/page--front.html.twig line 12

Other things ok

**Comment by IT-Cru** [comment]
Looks fine for me. Only point, but I think this already could be fixed later in newly used branch is the site name as H1 title. Perhaps SEO wants here site:name + site:slogan.

**Pull request merged**
