### PR TITLE
feature/INREL-3651

### PR DESCRIPTION
**Pull request by mgoedecke**
…NREL-3651

use value of seo description field for pinterest share description INREL-3651

### CODE REVIEW

**Comment by IT-Cru** [comment]
I think we have to do a little work on code for fallback image, because it is possible that image style is NOT created without correct itok query parameter, when image style "pinterest_fallback_teaser_image" does not already exists.

And in which image style is the image from field_pinterest_image displayed? I think this should be also a correct pinterest image style. Problem is that users sometime upload very big images.

**Comment by mgoedecke** [comment]
The field_pinterest_image was specifically requested without an image style so that the editor can upload any image and it will be shared unchanged.

Does each image style require a different itok?

**Comment by IT-Cru** [comment]
Perhaps we can build a helper function to get the URL of the sharing image which get URL directly from field_teaser_media (I think this is our current source of sharing image url) and generate then the pinterest_fallback_teaser_image image style URL.

Code for this can be found in image_style_warmer module.

**Comment by mgoedecke** [comment]
I think I tried this, but didn't have access to the actual image entity. 
If I remember correctly there is only the image url available in the preprocess function

**Comment by mgoedecke** [comment]
@IT-Cru updated to use existing MediaHelper::getImageUrlFromMediaReference function

**Comment by IT-Cru** [comment]
Why we not use in infinite_theme:323 also the previous filtered $entity variable?

Why we have here different ways to get the entity out of $variables?

Once we use $variables['element']['#parent']['#node'] or ..['#taxonomy_term'] and later $variables['parent']['#node']. Here we use only node entity, but we also have taxonomy_term entities with a field_teaser_media.

I think a check of the fallback return value is also missing. For example when field_teaser_media is empty.

**Pull request merged**
