### PR TITLE
Add assets

### PR DESCRIPTION
**Pull request by tjwelde**
This PR adds required libraries and compiled css to the repo

### CODE REVIEW

**Comment by landsman** [comment]
Omg, why are you was add compiled css? 👎 👎 👎
You must have npm for install Thunder, bower etc. It doesn't make sense.

**Comment by tjwelde** [comment]
As I already told you, we have to support the old `drush make` workflow.

**Comment by dbosen** [comment]
It must be possible to just download the tarball from drupal.org and be ready to use it. And drupal.org does not build css. We need to provide it.

**Comment by landsman** [comment]
@dbosen Is Infinite as is without infinite-module useful?

**Comment by dbosen** [comment]
no its not

**Comment by landsman** [comment]
@dbosen Why would I want downloading it from drupal.org? I was think that you prefer "composer-way".

**Comment by dbosen** [comment]
Yes we promote the composer way, but we are also an official drupal.org distribution and have to adhere to their rules. This is nothing we want to change.

**Comment by dbosen** [comment]
Just to make sure what I am talking about, I am talking about the download link on that page: https://www.drupal.org/project/thunder
That zip file is build by drupal.org and needs to contain the css to be usable.

**Comment by landsman** [comment]
sad, ok ...

**Comment by landsman** [comment]
What about create special branche for making releases on Drupal.org, where can be all these downloaded libs? For composer users we can have clean repository :-)

**Pull request merged**
